// SPDX-License-Identifier: AGPL-3.0-or-later
//! `design-tokens-gen` — deterministic generator for Pangolin's UI
//! design tokens (MVP-4-A).
//!
//! Reads the canonical JSON source at
//! `apps/design-tokens/tokens.json` (resolved via `CARGO_MANIFEST_DIR`
//! so the binary works the same regardless of the caller's CWD) and
//! emits two artifacts under `apps/design-tokens/`:
//!
//! * `dist/tokens.css` — CSS custom properties wrapped in a `:root { }`
//!   block (plus a `[data-theme="dark"] { }` block for the dark
//!   overrides of theme-pair colors). Consumed by the Tauri `WebView`
//!   and the Chromium MV3 extension popup.
//! * `src/lib.rs` — the `pangolin-design-tokens` Rust library crate's
//!   `lib.rs`, exposing one `pub const` per token (e.g.
//!   `COLOR_ACCENT_PRIMARY: &str = "#F2843E"`,
//!   `SPACE_4: &str = "1rem"`, `FONT_WEIGHT_REGULAR: u16 = 400`).
//!   Consumed by any Rust-side rendering surface (notifications,
//!   system-tray badges, native fallbacks).
//!
//! The generator is **deterministic**: same input → byte-identical
//! output across runs (`BTreeMap` iteration; no `HashMap`; sorted keys
//! everywhere). The plan-LOCK (`docs/issue-plans/mvp4-a-design-tokens.md`)
//! is explicit about this — the dist files are committed to git and
//! CI re-runs the generator + `git diff --exit-status apps/design-tokens/`
//! to catch drift.
//!
//! The generator REJECTS values that look like secrets (long random
//! hex / base64) with a typed `GeneratorError::SecretShapedValue` so
//! a designer cannot accidentally check a private key into the tokens
//! file (L1 / L3 fail-closed paranoia).

#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;
use std::process::ExitCode;

use serde_json::Value;

/// Schema version this generator supports. Bumping requires a
/// generator code change + a migration plan; see plan §3 / §6.
const SUPPORTED_SCHEMA_VERSION: u64 = 1;

/// File header stamped onto both emitted artifacts. The "DO NOT EDIT
/// BY HAND" line keeps the dist files honest in PR review: the CI
/// `design-tokens-up-to-date` job is the enforcement, this comment is
/// the courtesy notice.
const GENERATED_BANNER: &str =
    "GENERATED by tools/design-tokens-gen \u{2014} DO NOT EDIT BY HAND.\n\
     Source: apps/design-tokens/tokens.json  schema_version=1";

/// Typed errors. Each variant maps 1:1 to a plan-LOCK invariant:
/// schema-version gate (L3 fail-closed), secret-shape rejection (L1
/// zero-secret), missing-category gate (L3 fail-closed), I/O failure.
#[derive(Debug)]
pub enum GeneratorError {
    /// `schema_version` missing, non-integer, or not equal to
    /// [`SUPPORTED_SCHEMA_VERSION`].
    UnsupportedSchemaVersion {
        found: Option<u64>,
    },
    /// A leaf value matched the secret-shape heuristic (long contiguous
    /// hex or base64). The token path is included so the designer
    /// knows where to look.
    SecretShapedValue {
        path: String,
        sample_len: usize,
    },
    /// A required top-level category was missing or had the wrong
    /// shape. Plan §3 enumerates the categories; the generator gates
    /// fail-closed against a malformed source file.
    MissingOrInvalidCategory {
        category: &'static str,
        reason: String,
    },
    /// A leaf value was not a string or integer (the only token leaf
    /// types we accept).
    InvalidLeafType {
        path: String,
        kind: &'static str,
    },
    /// Anything else that bubbled up from `serde_json` or `std::io`.
    Io(String),
    Json(String),
}

impl std::fmt::Display for GeneratorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnsupportedSchemaVersion { found } => {
                write!(
                    f,
                    "unsupported design-tokens schema_version: found={found:?}, supported={SUPPORTED_SCHEMA_VERSION}"
                )
            }
            Self::SecretShapedValue { path, sample_len } => {
                write!(
                    f,
                    "value at {path} looks like a secret (length={sample_len}, matched long-hex or base64 heuristic); \
                     design tokens are non-secret by definition — refuse to emit"
                )
            }
            Self::MissingOrInvalidCategory { category, reason } => {
                write!(f, "category {category}: {reason}")
            }
            Self::InvalidLeafType { path, kind } => {
                write!(
                    f,
                    "leaf at {path} has unsupported type {kind} (expected string or integer)"
                )
            }
            Self::Io(m) | Self::Json(m) => f.write_str(m),
        }
    }
}

impl std::error::Error for GeneratorError {}

impl From<std::io::Error> for GeneratorError {
    fn from(e: std::io::Error) -> Self {
        Self::Io(e.to_string())
    }
}

impl From<serde_json::Error> for GeneratorError {
    fn from(e: serde_json::Error) -> Self {
        Self::Json(e.to_string())
    }
}

/// A token leaf is either a string (most values) or a small integer
/// (font weights). We carry the original JSON form so the emitters
/// can format CSS vs Rust appropriately (Rust `&str` vs `u16`).
#[derive(Debug, Clone, PartialEq, Eq)]
enum Leaf {
    Str(String),
    Int(u64),
}

impl Leaf {
    fn css_repr(&self) -> String {
        match self {
            Self::Str(s) => s.clone(),
            Self::Int(n) => n.to_string(),
        }
    }

    fn rust_type(&self) -> &'static str {
        match self {
            Self::Str(_) => "&str",
            Self::Int(_) => "u16",
        }
    }

    fn rust_repr(&self) -> String {
        match self {
            // We use a debug-quoted form so embedded single-quotes
            // (e.g. `'Inter', system-ui`) survive verbatim. Backslash
            // and double-quote get escaped per Rust's `Debug for str`.
            Self::Str(s) => format!("{s:?}"),
            Self::Int(n) => n.to_string(),
        }
    }
}

/// A single token in normalized form, ready for emission. Theme-pair
/// colors expand into TWO entries (one with `theme=Some(Light)`, one
/// with `theme=Some(Dark)`); plain tokens have `theme=None`.
#[derive(Debug, Clone)]
struct Token {
    /// CSS variable name without the leading `--` (e.g. `color-accent-primary`).
    css_name: String,
    /// Rust constant name (e.g. `COLOR_ACCENT_PRIMARY`).
    rust_name: String,
    value: Leaf,
    theme: Option<Theme>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Theme {
    Light,
    Dark,
}

/// Group tokens by category for emit ordering. The order itself is
/// the canonical emit order (color → typography → spacing → radius →
/// elevation → motion); inside each category, tokens are sorted by
/// `css_name` for byte-identical determinism.
#[derive(Debug, Clone, Copy)]
enum Category {
    Color,
    Typography,
    Spacing,
    Radius,
    Elevation,
    Motion,
}

impl Category {
    const ALL: [Self; 6] = [
        Self::Color,
        Self::Typography,
        Self::Spacing,
        Self::Radius,
        Self::Elevation,
        Self::Motion,
    ];

    fn json_key(self) -> &'static str {
        match self {
            Self::Color => "color",
            Self::Typography => "typography",
            Self::Spacing => "spacing",
            Self::Radius => "radius",
            Self::Elevation => "elevation",
            Self::Motion => "motion",
        }
    }

    fn banner(self) -> &'static str {
        match self {
            Self::Color => "COLOR",
            Self::Typography => "TYPOGRAPHY",
            Self::Spacing => "SPACING",
            Self::Radius => "RADIUS",
            Self::Elevation => "ELEVATION (CSS box-shadow stacks)",
            Self::Motion => "MOTION",
        }
    }
}

/// Resolve the source path. We use `CARGO_MANIFEST_DIR` (the
/// generator's own crate dir, `tools/design-tokens-gen`) and walk up
/// two levels to the workspace root. That means `cargo run -p
/// design-tokens-gen` works identically from any CWD.
fn workspace_root() -> PathBuf {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set by cargo");
    PathBuf::from(manifest_dir)
        .parent() // tools/
        .and_then(std::path::Path::parent) // workspace root
        .expect("tools/design-tokens-gen lives two levels below the workspace root")
        .to_path_buf()
}

fn main() -> ExitCode {
    let root = workspace_root();
    let json_path = root.join("apps").join("design-tokens").join("tokens.json");
    let css_out = root
        .join("apps")
        .join("design-tokens")
        .join("dist")
        .join("tokens.css");
    let rust_out = root
        .join("apps")
        .join("design-tokens")
        .join("src")
        .join("lib.rs");

    let raw = match std::fs::read_to_string(&json_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("design-tokens-gen: read {}: {e}", json_path.display());
            return ExitCode::from(2);
        }
    };

    let (css, rust) = match generate(&raw) {
        Ok(p) => p,
        Err(e) => {
            eprintln!("design-tokens-gen: {e}");
            return ExitCode::from(2);
        }
    };

    if let Some(p) = css_out.parent() {
        if let Err(e) = std::fs::create_dir_all(p) {
            eprintln!("design-tokens-gen: mkdir {}: {e}", p.display());
            return ExitCode::from(2);
        }
    }
    if let Err(e) = std::fs::write(&css_out, css) {
        eprintln!("design-tokens-gen: write {}: {e}", css_out.display());
        return ExitCode::from(2);
    }
    if let Err(e) = std::fs::write(&rust_out, rust) {
        eprintln!("design-tokens-gen: write {}: {e}", rust_out.display());
        return ExitCode::from(2);
    }

    println!(
        "design-tokens-gen: wrote {} + {}",
        css_out.display(),
        rust_out.display()
    );
    ExitCode::SUCCESS
}

/// The pure-function core: parse JSON source → emit (css, rust). No
/// I/O. Tested in `mod tests`.
fn generate(raw: &str) -> Result<(String, String), GeneratorError> {
    let value: Value = serde_json::from_str(raw)?;
    let obj = value
        .as_object()
        .ok_or_else(|| GeneratorError::Json("source root must be a JSON object".into()))?;

    // Schema-version gate (fail-closed per L3).
    let schema_version = obj.get("schema_version").and_then(Value::as_u64);
    if schema_version != Some(SUPPORTED_SCHEMA_VERSION) {
        return Err(GeneratorError::UnsupportedSchemaVersion {
            found: schema_version,
        });
    }

    // Walk each category in canonical order, building (category, sorted-tokens) pairs.
    // BTreeMap-equivalent ordering: we sort inside each category by css_name.
    let mut by_category: Vec<(Category, Vec<Token>)> = Vec::with_capacity(Category::ALL.len());
    for cat in Category::ALL {
        let node =
            obj.get(cat.json_key())
                .ok_or_else(|| GeneratorError::MissingOrInvalidCategory {
                    category: cat.json_key(),
                    reason: "missing".into(),
                })?;
        let mut tokens = walk_category(cat, node)?;
        // Deterministic intra-category order.
        tokens.sort_by(|a, b| {
            // Sort by css_name first; within a theme-pair, Light before Dark.
            a.css_name
                .cmp(&b.css_name)
                .then_with(|| theme_rank(a.theme).cmp(&theme_rank(b.theme)))
        });
        by_category.push((cat, tokens));
    }

    let css = emit_css(&by_category);
    let rust = emit_rust(&by_category);
    Ok((css, rust))
}

fn theme_rank(t: Option<Theme>) -> u8 {
    match t {
        None => 0,
        Some(Theme::Light) => 1,
        Some(Theme::Dark) => 2,
    }
}

// Per-category walkers + the `walk_category` dispatcher live in this
// section. The JSON-key → CSS-name mapping is:
//
// * `color.{neutral|accent}.{key}` → `--color-{group}-{key}`
//   (the `accent` group prefix is preserved in the CSS name so
//   `accent.primary` becomes `--color-accent-primary`; `neutral.0`
//   becomes `--color-neutral-0`). `color.semantic.{key}` with a
//   `{light, dark}` pair expands to a theme-pair token.
// * `typography.font_family.{key}` → `--font-family-{key}`.
// * `typography.size.{key}` → `--font-size-{key}`.
// * `typography.weight.{key}` → `--font-weight-{key}` (integer).
// * `typography.line_height.{key}` → `--font-line-height-{key}`.
// * `spacing.{key}` → `--space-{key}`.
// * `radius.{key}` → `--radius-{key}`.
// * `elevation.{key}` → `--shadow-{key}` (the CSS convention; plan §3.2).
// * `motion.duration.{key}` → `--motion-duration-{key}`.
// * `motion.easing.{key}` → `--motion-easing-{key}`.

/// Helper: require a JSON value to be an object, or fail with a
/// typed `MissingOrInvalidCategory` carrying the category + reason.
fn require_object<'a>(
    cat: Category,
    reason: &str,
    node: &'a Value,
) -> Result<&'a serde_json::Map<String, Value>, GeneratorError> {
    node.as_object()
        .ok_or_else(|| GeneratorError::MissingOrInvalidCategory {
            category: cat.json_key(),
            reason: reason.into(),
        })
}

/// Helper: deterministic-iteration view of a JSON object.
fn sorted_view(obj: &serde_json::Map<String, Value>) -> BTreeMap<&String, &Value> {
    obj.iter().collect()
}

fn walk_color(obj: &serde_json::Map<String, Value>) -> Result<Vec<Token>, GeneratorError> {
    let mut out = Vec::new();
    for group in ["neutral", "accent", "semantic"] {
        let Some(group_node) = obj.get(group) else {
            continue;
        };
        let group_obj = require_object(
            Category::Color,
            &format!("color.{group} must be an object"),
            group_node,
        )?;
        for (key, val) in sorted_view(group_obj) {
            if let Some(pair) = val.as_object() {
                if pair.contains_key("light") && pair.contains_key("dark") {
                    // semantic colors collapse the group prefix in the CSS
                    // name (plan §3.2: `--color-surface`, not
                    // `--color-semantic-surface`); Rust gets the same
                    // collapsed name + LIGHT/DARK suffix.
                    let collapsed_css = format!("color-{key}");
                    let collapsed_rust = rust_ident_from_css(&collapsed_css);
                    let light =
                        leaf_from_json(&format!("color.{group}.{key}.light"), &pair["light"])?;
                    let dark = leaf_from_json(&format!("color.{group}.{key}.dark"), &pair["dark"])?;
                    out.push(Token {
                        css_name: collapsed_css.clone(),
                        rust_name: format!("{collapsed_rust}_LIGHT"),
                        value: light,
                        theme: Some(Theme::Light),
                    });
                    out.push(Token {
                        css_name: collapsed_css,
                        rust_name: format!("{collapsed_rust}_DARK"),
                        value: dark,
                        theme: Some(Theme::Dark),
                    });
                    continue;
                }
            }
            let css_name = format!("color-{group}-{key}");
            let rust_name = rust_ident_from_css(&css_name);
            let leaf = leaf_from_json(&format!("color.{group}.{key}"), val)?;
            out.push(Token {
                css_name,
                rust_name,
                value: leaf,
                theme: None,
            });
        }
    }
    Ok(out)
}

fn walk_typography(obj: &serde_json::Map<String, Value>) -> Result<Vec<Token>, GeneratorError> {
    let mut out = Vec::new();
    for (sub, prefix) in [
        ("font_family", "font-family"),
        ("size", "font-size"),
        ("weight", "font-weight"),
        ("line_height", "font-line-height"),
    ] {
        let Some(sub_node) = obj.get(sub) else {
            continue;
        };
        let sub_obj = require_object(
            Category::Typography,
            &format!("typography.{sub} must be an object"),
            sub_node,
        )?;
        for (key, val) in sorted_view(sub_obj) {
            let css_name = format!("{prefix}-{key}");
            let rust_name = rust_ident_from_css(&css_name);
            let leaf = leaf_from_json(&format!("typography.{sub}.{key}"), val)?;
            out.push(Token {
                css_name,
                rust_name,
                value: leaf,
                theme: None,
            });
        }
    }
    Ok(out)
}

fn walk_flat(
    obj: &serde_json::Map<String, Value>,
    css_prefix: &str,
    json_prefix: &str,
) -> Result<Vec<Token>, GeneratorError> {
    let mut out = Vec::new();
    for (key, val) in sorted_view(obj) {
        let css_name = format!("{css_prefix}-{key}");
        let rust_name = rust_ident_from_css(&css_name);
        let leaf = leaf_from_json(&format!("{json_prefix}.{key}"), val)?;
        out.push(Token {
            css_name,
            rust_name,
            value: leaf,
            theme: None,
        });
    }
    Ok(out)
}

fn walk_motion(obj: &serde_json::Map<String, Value>) -> Result<Vec<Token>, GeneratorError> {
    let mut out = Vec::new();
    for sub in ["duration", "easing"] {
        let Some(sub_node) = obj.get(sub) else {
            continue;
        };
        let sub_obj = require_object(
            Category::Motion,
            &format!("motion.{sub} must be an object"),
            sub_node,
        )?;
        for (key, val) in sorted_view(sub_obj) {
            let css_name = format!("motion-{sub}-{key}");
            let rust_name = rust_ident_from_css(&css_name);
            let leaf = leaf_from_json(&format!("motion.{sub}.{key}"), val)?;
            out.push(Token {
                css_name,
                rust_name,
                value: leaf,
                theme: None,
            });
        }
    }
    Ok(out)
}

fn walk_category(cat: Category, node: &Value) -> Result<Vec<Token>, GeneratorError> {
    let obj = require_object(cat, "expected an object", node)?;
    match cat {
        Category::Color => walk_color(obj),
        Category::Typography => walk_typography(obj),
        Category::Spacing => walk_flat(obj, "space", "spacing"),
        Category::Radius => walk_flat(obj, "radius", "radius"),
        Category::Elevation => walk_flat(obj, "shadow", "elevation"),
        Category::Motion => walk_motion(obj),
    }
}

/// Parse a single JSON leaf into our normalized [`Leaf`] enum, and
/// run the secret-shape sniffer on string leaves.
fn leaf_from_json(path: &str, val: &Value) -> Result<Leaf, GeneratorError> {
    if let Some(s) = val.as_str() {
        reject_if_secret_shaped(path, s)?;
        return Ok(Leaf::Str(s.to_string()));
    }
    if let Some(n) = val.as_u64() {
        return Ok(Leaf::Int(n));
    }
    let kind = if val.is_null() {
        "null"
    } else if val.is_array() {
        "array"
    } else if val.is_object() {
        "object"
    } else if val.is_boolean() {
        "boolean"
    } else if val.is_f64() {
        "float"
    } else if val.is_i64() {
        "signed-integer"
    } else {
        "unknown"
    };
    Err(GeneratorError::InvalidLeafType {
        path: path.into(),
        kind,
    })
}

/// Secret-shape heuristic (L1 / paranoia gate). A token value is
/// rejected if it contains a long (>=32 char) contiguous run of
/// either hex digits or base64-alphabet characters with no embedded
/// punctuation/whitespace. Short hex (color codes like `#F2843E`,
/// 7 chars including `#`) and short tokens (numbers, units, font
/// stacks with spaces and commas) pass cleanly.
///
/// This is a paranoia rail — not a cryptographic secret detector.
/// It exists to refuse the obvious failure mode where someone pastes
/// a private-key hex string into the tokens file by accident.
fn reject_if_secret_shaped(path: &str, s: &str) -> Result<(), GeneratorError> {
    const MIN_RUN: usize = 32;
    let mut hex_run = 0_usize;
    let mut b64_run = 0_usize;
    for c in s.chars() {
        if c.is_ascii_hexdigit() {
            hex_run += 1;
            if hex_run >= MIN_RUN {
                return Err(GeneratorError::SecretShapedValue {
                    path: path.into(),
                    sample_len: s.len(),
                });
            }
        } else {
            hex_run = 0;
        }
        if c.is_ascii_alphanumeric() || c == '+' || c == '/' || c == '=' {
            b64_run += 1;
            if b64_run >= MIN_RUN {
                return Err(GeneratorError::SecretShapedValue {
                    path: path.into(),
                    sample_len: s.len(),
                });
            }
        } else {
            b64_run = 0;
        }
    }
    Ok(())
}

/// Convert a CSS variable name (kebab-case) into a Rust constant
/// identifier (`UPPER_SNAKE_CASE`). Dashes become underscores; the
/// result is uppercased.
fn rust_ident_from_css(css_name: &str) -> String {
    css_name.replace('-', "_").to_uppercase()
}

fn emit_css(by_category: &[(Category, Vec<Token>)]) -> String {
    let mut out = String::with_capacity(4096);
    writeln!(out, "/* {} */", GENERATED_BANNER.replace('\n', "\n   ")).unwrap();
    writeln!(out, ":root {{").unwrap();
    for (cat, tokens) in by_category {
        writeln!(out, "  /* --- {} --- */", cat.banner()).unwrap();
        for tok in tokens {
            // Theme=Dark variants go in the [data-theme="dark"] block,
            // not under :root.
            if tok.theme == Some(Theme::Dark) {
                continue;
            }
            writeln!(out, "  --{}: {};", tok.css_name, tok.value.css_repr()).unwrap();
        }
    }
    writeln!(out, "}}").unwrap();

    // Dark overrides (theme-pair colors only).
    let dark: Vec<&Token> = by_category
        .iter()
        .flat_map(|(_, v)| v.iter())
        .filter(|t| t.theme == Some(Theme::Dark))
        .collect();
    if !dark.is_empty() {
        writeln!(out).unwrap();
        writeln!(out, "[data-theme=\"dark\"] {{").unwrap();
        for tok in dark {
            writeln!(out, "  --{}: {};", tok.css_name, tok.value.css_repr()).unwrap();
        }
        writeln!(out, "}}").unwrap();
    }
    out
}

fn emit_rust(by_category: &[(Category, Vec<Token>)]) -> String {
    let mut out = String::with_capacity(4096);
    writeln!(out, "// SPDX-License-Identifier: AGPL-3.0-or-later").unwrap();
    writeln!(out, "// {}", GENERATED_BANNER.replace('\n', "\n// ")).unwrap();
    writeln!(out, "#![forbid(unsafe_code)]").unwrap();
    writeln!(out, "#![allow(clippy::unreadable_literal)]").unwrap();
    writeln!(out, "//! Generated Pangolin UI design-token constants.").unwrap();
    writeln!(
        out,
        "//! Source: `apps/design-tokens/tokens.json`. Re-generate via `cargo run -p design-tokens-gen`."
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// The schema version of the source `tokens.json` that produced this file."
    )
    .unwrap();
    writeln!(
        out,
        "pub const SCHEMA_VERSION: u8 = {SUPPORTED_SCHEMA_VERSION};"
    )
    .unwrap();
    for (cat, tokens) in by_category {
        writeln!(out).unwrap();
        writeln!(out, "// --- {} ---", cat.banner()).unwrap();
        for tok in tokens {
            writeln!(
                out,
                "pub const {}: {} = {};",
                tok.rust_name,
                tok.value.rust_type(),
                tok.value.rust_repr()
            )
            .unwrap();
        }
    }
    out
}

// =====================================================================
// Tests
// =====================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// The canonical example used across multiple tests. Mirrors plan
    /// §3.1's example structure but is reduced to a parseable minimum
    /// where useful.
    const EXAMPLE_JSON: &str = r##"{
      "_comment": "first-pass values; refined at MVP-4-D + closed beta",
      "$schema": "https://pangolin.example/schemas/design-tokens-v1.json",
      "schema_version": 1,
      "color": {
        "neutral": {
          "0": "#0A0A0B",
          "50": "#141416",
          "900": "#FAFAFB"
        },
        "accent": {
          "primary": "#F2843E",
          "primary-hover": "#E0732D"
        },
        "semantic": {
          "surface": { "light": "#FFFFFF", "dark": "#141416" },
          "text":    { "light": "#0A0A0B", "dark": "#FAFAFB" }
        }
      },
      "typography": {
        "font_family": { "sans": "'Inter', sans-serif" },
        "size": { "base": "1rem", "2xl": "1.5rem" },
        "weight": { "regular": 400, "bold": 700 },
        "line_height": { "base": "1.5" }
      },
      "spacing": { "0": "0", "4": "1rem" },
      "radius": { "sm": "4px", "full": "9999px" },
      "elevation": { "none": "none", "sm": "0 1px 2px rgba(0,0,0,0.06)" },
      "motion": {
        "duration": { "fast": "100ms" },
        "easing": { "standard": "cubic-bezier(0.2, 0, 0, 1)" }
      }
    }"##;

    #[test]
    fn parse_then_emit_then_reparse_round_trips() {
        let (css, rust) = generate(EXAMPLE_JSON).expect("generate");

        // CSS-side: extract every `--name: value;` line under :root + dark.
        let css_pairs = parse_css_vars(&css);

        // Rust-side: extract every `pub const NAME: TYPE = "value";`
        // or `... = 400;` line.
        let rust_pairs = parse_rust_consts(&rust);

        // Spot-check a stable set of keys we expect to land.
        // Theme-pair colors (LIGHT goes to :root, DARK to dark block).
        assert_eq!(
            css_pairs.get("--color-surface").map(String::as_str),
            Some("#FFFFFF"),
            "css :root --color-surface must be the LIGHT value"
        );
        assert_eq!(
            rust_pairs.get("COLOR_SURFACE_LIGHT").map(String::as_str),
            Some("\"#FFFFFF\"")
        );
        assert_eq!(
            rust_pairs.get("COLOR_SURFACE_DARK").map(String::as_str),
            Some("\"#141416\"")
        );

        // Accent (no theme split).
        assert_eq!(
            css_pairs.get("--color-accent-primary").map(String::as_str),
            Some("#F2843E")
        );
        assert_eq!(
            rust_pairs.get("COLOR_ACCENT_PRIMARY").map(String::as_str),
            Some("\"#F2843E\"")
        );

        // Spacing.
        assert_eq!(css_pairs.get("--space-4").map(String::as_str), Some("1rem"));
        assert_eq!(
            rust_pairs.get("SPACE_4").map(String::as_str),
            Some("\"1rem\"")
        );

        // Typography integer weight.
        assert_eq!(
            css_pairs.get("--font-weight-regular").map(String::as_str),
            Some("400")
        );
        assert_eq!(
            rust_pairs.get("FONT_WEIGHT_REGULAR").map(String::as_str),
            Some("400")
        );

        // Motion (composite key).
        assert_eq!(
            css_pairs.get("--motion-duration-fast").map(String::as_str),
            Some("100ms")
        );
        assert_eq!(
            rust_pairs.get("MOTION_DURATION_FAST").map(String::as_str),
            Some("\"100ms\"")
        );

        // Elevation → `shadow-` prefix.
        assert_eq!(
            css_pairs.get("--shadow-sm").map(String::as_str),
            Some("0 1px 2px rgba(0,0,0,0.06)")
        );

        // Schema-version constant lands.
        assert_eq!(
            rust_pairs.get("SCHEMA_VERSION").map(String::as_str),
            Some("1")
        );
    }

    #[test]
    fn identifier_canonicalization() {
        // CSS preserves dashes; Rust replaces with underscores + uppercases.
        assert_eq!(
            rust_ident_from_css("color-accent-primary"),
            "COLOR_ACCENT_PRIMARY"
        );
        assert_eq!(rust_ident_from_css("space-4"), "SPACE_4");
        assert_eq!(rust_ident_from_css("font-size-base"), "FONT_SIZE_BASE");
        assert_eq!(rust_ident_from_css("font-size-2xl"), "FONT_SIZE_2XL");
        assert_eq!(
            rust_ident_from_css("motion-easing-standard"),
            "MOTION_EASING_STANDARD"
        );
        assert_eq!(rust_ident_from_css("color-neutral-0"), "COLOR_NEUTRAL_0");
    }

    #[test]
    fn unknown_schema_version_rejected() {
        let bad = EXAMPLE_JSON.replace("\"schema_version\": 1", "\"schema_version\": 99");
        let err = generate(&bad).expect_err("schema_version=99 must reject");
        match err {
            GeneratorError::UnsupportedSchemaVersion { found: Some(99) } => {}
            other => panic!("wrong error variant: {other:?}"),
        }
    }

    #[test]
    fn missing_schema_version_rejected() {
        let bad = EXAMPLE_JSON.replace("\"schema_version\": 1,", "");
        let err = generate(&bad).expect_err("missing schema_version must reject");
        match err {
            GeneratorError::UnsupportedSchemaVersion { found: None } => {}
            other => panic!("wrong error variant: {other:?}"),
        }
    }

    #[test]
    fn secret_shaped_value_rejected() {
        // Inject a 64-char hex string (private-key-shaped) into a token.
        // Note: the heuristic looks for a CONTIGUOUS hex run >= 32 chars.
        let bad = EXAMPLE_JSON.replace(
            "\"primary\": \"#F2843E\"",
            "\"primary\": \"aabbccddeeff0011223344556677889900112233445566778899aabbccddeeff\"",
        );
        let err = generate(&bad).expect_err("64-hex-char value must reject");
        match err {
            GeneratorError::SecretShapedValue { .. } => {}
            other => panic!("wrong error variant: {other:?}"),
        }
    }

    #[test]
    fn secret_shaped_base64_rejected() {
        // 44-char base64 (a 32-byte key, padded). Contains only
        // alphanumerics so it also satisfies the base64-run rail.
        let bad = EXAMPLE_JSON.replace(
            "\"primary\": \"#F2843E\"",
            "\"primary\": \"YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5\"",
        );
        let err = generate(&bad).expect_err("base64-shaped value must reject");
        match err {
            GeneratorError::SecretShapedValue { .. } => {}
            other => panic!("wrong error variant: {other:?}"),
        }
    }

    #[test]
    fn short_hex_color_codes_pass() {
        // 6 hex chars (#F2843E) and 7 with the # sign must NOT trip
        // the secret-shape rail. The example as-is contains these;
        // if it generated, that's the proof.
        let (_css, _rust) = generate(EXAMPLE_JSON).expect("short hex color codes are fine");
    }

    #[test]
    fn deterministic_emit() {
        let first = generate(EXAMPLE_JSON).expect("first");
        let second = generate(EXAMPLE_JSON).expect("second");
        let third = generate(EXAMPLE_JSON).expect("third");
        assert_eq!(first, second, "two runs must be byte-identical");
        assert_eq!(second, third, "three runs must be byte-identical");
    }

    #[test]
    fn theme_pair_emits_both_blocks() {
        let (css, _rust) = generate(EXAMPLE_JSON).expect("generate");
        // The :root block holds the LIGHT value for theme-pair colors.
        assert!(
            css.contains("  --color-surface: #FFFFFF;"),
            "expected light value of --color-surface under :root, got: {css}"
        );
        // The dark block holds the DARK override.
        assert!(
            css.contains("[data-theme=\"dark\"] {"),
            "expected a [data-theme=\"dark\"] block, got: {css}"
        );
        assert!(
            css.contains("  --color-surface: #141416;"),
            "expected dark override of --color-surface, got: {css}"
        );
    }

    #[test]
    fn css_root_block_present_with_banner() {
        let (css, _rust) = generate(EXAMPLE_JSON).expect("generate");
        assert!(css.contains("GENERATED by tools/design-tokens-gen"));
        assert!(css.contains(":root {"));
        assert!(css.trim_end().ends_with('}'));
    }

    #[test]
    fn rust_module_has_spdx_and_forbid_unsafe() {
        let (_css, rust) = generate(EXAMPLE_JSON).expect("generate");
        assert!(rust.contains("SPDX-License-Identifier: AGPL-3.0-or-later"));
        assert!(rust.contains("#![forbid(unsafe_code)]"));
        assert!(rust.contains("pub const SCHEMA_VERSION: u8 = 1;"));
    }

    // ----- Helpers used by parse_then_emit_then_reparse_round_trips -----

    /// Tiny `:root { --k: v; }` parser. Lenient: ignores comments,
    /// whitespace, block boundaries. Returns one map covering both
    /// `:root` and `[data-theme="dark"]` blocks — the dark block
    /// OVERWRITES `:root` entries for the theme-pair colors. Since
    /// the round-trip test only spot-checks specific keys, and
    /// theme-pair keys are checked separately via direct `css.contains`,
    /// this is fine.
    fn parse_css_vars(css: &str) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        for line in css.lines() {
            let trimmed = line.trim();
            // Match `--name: value;` lines.
            if let Some(rest) = trimmed.strip_prefix("--") {
                if let Some(semi) = rest.rfind(';') {
                    let kv = &rest[..semi];
                    if let Some(colon) = kv.find(':') {
                        let name = format!("--{}", kv[..colon].trim());
                        let val = kv[colon + 1..].trim().to_string();
                        // For theme-pair keys, the dark block re-inserts.
                        // Tests that care about per-block values inspect
                        // the raw `css` string directly via .contains().
                        // For non-theme keys (the bulk of round-trip
                        // spot-checks), the dark block does not touch them.
                        // To preserve the :root (LIGHT) value for theme keys
                        // in the round-trip spot-check, we only insert if
                        // the key is not already present.
                        out.entry(name).or_insert(val);
                    }
                }
            }
        }
        out
    }

    /// Tiny `pub const NAME: TYPE = expr;` parser. Returns the raw
    /// expression text (so `"#FFFFFF"` keeps its quotes, `400` does not).
    fn parse_rust_consts(emitted: &str) -> BTreeMap<String, String> {
        let mut out = BTreeMap::new();
        for line in emitted.lines() {
            let trimmed = line.trim();
            let Some(decl) = trimmed.strip_prefix("pub const ") else {
                continue;
            };
            let Some(colon) = decl.find(':') else {
                continue;
            };
            let name = decl[..colon].trim().to_string();
            let Some(eq) = decl.find('=') else { continue };
            let Some(semi) = decl.rfind(';') else {
                continue;
            };
            if semi <= eq + 1 {
                continue;
            }
            let val = decl[eq + 1..semi].trim().to_string();
            out.insert(name, val);
        }
        out
    }
}
