// SPDX-License-Identifier: AGPL-3.0-or-later
//! Pairing-payload TRANSPORT codec (#106e-2).
//!
//! The fixed-layout, zero-serde, length- + checksum-validated, version-gated
//! payload the device-add handshake moves between the new device and the
//! existing manager device. The HOST renders the byte form as a QR (for camera
//! devices) and/or copy-pastes the text form (for camera-less devices); the
//! Rust layer is transport-agnostic — it ONLY produces/consumes bytes + the
//! string + the SAS. NO network relay.
//!
//! ## Why a hand-rolled codec (L4, L6)
//!
//! Per §0a Q-carrier + L6 (`docs/issue-plans/106e2-pairing-transport-sas.md`):
//! ZERO new external crates, NO serde anywhere on the secret-adjacent path,
//! fixed-offset (so a tampered byte can never silently re-parse as a different
//! field, the `#103`/byte-identity discipline). Adds a [`SCHEMA_VERSION`] pin
//! + a [`DOMAIN`] prefix + a 4-byte SHA-256 truncated checksum on the text
//! form so any drift (length / domain / version / checksum / encoding) fails
//! CLOSED with a typed [`PairingTransportError`] — never silent.
//!
//! ## The wire layout
//!
//! ```text
//! payload_bytes =
//!     DOMAIN(D bytes, fixed)
//!  || schema_version (1 B, == SCHEMA_VERSION)
//!  || vault_id       (VAULT_ID_LEN = 32 B)
//!  || device_id      (DEVICE_ID_LEN = 32 B)
//!  || x25519_pairing_pub (X25519_KEY_LEN = 32 B)
//!  || signer         (20 B, the new device's secp256k1 EVM address)
//!  || freshness_nonce (FRESHNESS_NONCE_LEN = 16 B, generated by the new device)
//! ```
//!
//! Total length = [`PAYLOAD_LEN`] = `DOMAIN.len() + 1 + 32 + 32 + 32 + 20 + 16`.
//!
//! The TEXT form is `base32_rfc4648_nopad(payload_bytes || sha256(payload_bytes)[..4])`
//! lowercased: pure `a-z` + `2-7`, no padding, ~ 142 chars at SCHEMA_VERSION 2.
//!
//! ## Invariants (L1, L2, L4 — `106e2-pairing-transport-sas.md`)
//!
//! - **L1.** Every field in the payload is NON-secret (pubkeys / ids /
//!   signer / freshness nonce). The X25519 pairing SECRET stays engine-side.
//! - **L4.** Fixed-offset, length-strict, version-gated. A drifted byte does
//!   NOT silently re-parse — every decode runs a 6-step gate (length, domain,
//!   version, field extraction, text checksum re-derive, text alphabet
//!   check). Re-encoding a decoded payload MUST round-trip byte-identical
//!   (a property test pins this).
//! - **L4 (errors carry no secrets).** [`PairingTransportError`] is
//!   deliberately coarse — five typed kinds, no payload bytes in any
//!   `Display`.

#![forbid(unsafe_code)]
// The pairing-transport codec is heavily documented (the wire layout + the L1/L4
// invariants need to be in-source). The doc-style pedantic lints below would
// require contorting the docs without security/correctness benefit; allow them
// at the module level. Substantive lints stay enforced.
#![allow(
    clippy::doc_markdown,
    clippy::too_long_first_doc_paragraph,
    clippy::doc_lazy_continuation
)]

use pangolin_crypto::escrow::X25519_KEY_LEN;
use pangolin_crypto::keys::VAULT_ID_LEN;

use pangolin_crypto::pairing::DEVICE_ID_LEN;

/// The 20-byte secp256k1 EVM address of the new device's signer
/// — bound INTO the payload because the manager's `add_device_v2`
/// authorizes this exact address on-chain.
pub const SIGNER_LEN: usize = 20;

/// The freshness nonce length in bytes (16 — same shape the SAS
/// derivation consumes; see [`pangolin_crypto::pairing::derive_sas`]).
///
/// Generated by the NEW device, sized to give 128-bit collision resistance
/// against a stale/replayed payload + a 6-digit SAS-domain hash that re-binds
/// it. Per §0a Q-c the new device originates the nonce; both devices' SAS
/// must derive over the SAME nonce, so the manager builds its own payload
/// USING the nonce it just received from the new device (see
/// [`crate::pairing_transport`] doc + the FFI `pairing_local_payload`).
pub const FRESHNESS_NONCE_LEN: usize = 16;

/// The pairing-payload domain-separator prefix.
///
/// Distinct from every existing HKDF info / domain string in the codebase
/// (`pangolin-vdk-wrap-v0`, `pangolin-recovery-wrap-v0`,
/// `pangolin-guardian-x25519-v0`, `pangolin-device-pair-x25519-v0`,
/// `pangolin-device-wrap-v0`, `pangolin-device-pair-seal-v0`,
/// `pangolin-pairing-sas-v0`). Pinned by a byte-identity test
/// (`pairing_transport_domain_distinct_from_other_domains`).
pub const DOMAIN: &[u8] = b"pangolin-pairing-payload-v0";

/// Pairing-payload schema version. Pinned to **2** (next after #106c's
/// `DeviceAuthFields v=1`). A decode against any other version fails
/// CLOSED with [`PairingTransportError::UnsupportedVersion`].
pub const SCHEMA_VERSION: u8 = 2;

/// Total exact byte length of an encoded payload (zero-serde, fixed-layout).
///
/// Decoding any byte slice whose length ≠ [`PAYLOAD_LEN`] fails CLOSED with
/// [`PairingTransportError::WrongLength`]. Pinned by
/// [`tests::payload_length_is_exact_constant`].
pub const PAYLOAD_LEN: usize = DOMAIN.len()
    + 1
    + VAULT_ID_LEN
    + DEVICE_ID_LEN
    + X25519_KEY_LEN
    + SIGNER_LEN
    + FRESHNESS_NONCE_LEN;

/// Length of the 4-byte truncated-SHA-256 checksum the TEXT form appends
/// before base32-encoding. NOT used for the byte form (the QR / host
/// renderer carries the byte form raw — its only consumer is
/// [`decode_bytes`], which length-strict-checks against [`PAYLOAD_LEN`]).
pub const TEXT_CHECKSUM_LEN: usize = 4;

/// The fixed-offset (byte form) start of `schema_version`.
const OFFSET_SCHEMA_VERSION: usize = DOMAIN.len();
/// The fixed-offset start of `vault_id`.
const OFFSET_VAULT_ID: usize = OFFSET_SCHEMA_VERSION + 1;
/// The fixed-offset start of `device_id`.
const OFFSET_DEVICE_ID: usize = OFFSET_VAULT_ID + VAULT_ID_LEN;
/// The fixed-offset start of `x25519_pairing_pub`.
const OFFSET_PAIRING_PUB: usize = OFFSET_DEVICE_ID + DEVICE_ID_LEN;
/// The fixed-offset start of `signer`.
const OFFSET_SIGNER: usize = OFFSET_PAIRING_PUB + X25519_KEY_LEN;
/// The fixed-offset start of `freshness_nonce`.
const OFFSET_FRESHNESS_NONCE: usize = OFFSET_SIGNER + SIGNER_LEN;

/// The NON-secret pairing payload — what the BYTE form encodes / the TEXT
/// form encodes after checksum-appending.
///
/// Every field is public context (pubkeys / ids / signer / nonce). NO
/// `Drop`/zeroize discipline is needed (zero secret-bearing field). Zero
/// serde — encode + decode go through [`encode_bytes`] / [`decode_bytes`]
/// (and their `_string` variants).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PairingPayload {
    /// The schema version this payload was encoded under — currently the
    /// pinned [`SCHEMA_VERSION`]. A decode of a different version fails
    /// CLOSED, so a decoded payload always carries the version this build
    /// supports.
    pub schema_version: u8,
    /// The 32-byte vault identifier the new device is joining (the existing
    /// vault's [`pangolin_store::Vault::vault_id`]). Bound into the
    /// payload so a manager's `vault_add_device` can reject a payload from
    /// a DIFFERENT vault (cross-vault replay defense).
    pub vault_id: [u8; VAULT_ID_LEN],
    /// The device's stable 32-byte identifier (GAP B —
    /// [`crate::device_add::device_id_from_device_key`]). Bound into the
    /// pairing seal header so a seal minted for B can only be opened by B.
    pub device_id: [u8; DEVICE_ID_LEN],
    /// The device's 32-byte X25519 pairing pubkey
    /// ([`pangolin_crypto::pairing::derive_x25519_pairing_key`]). What the
    /// manager [`crate::device_add::seal_vdk_to_new_device`] seals the VDK
    /// to.
    pub x25519_pairing_pub: [u8; X25519_KEY_LEN],
    /// The device's 20-byte secp256k1 EVM signer address (the
    /// `RevisionLogV2` authorized-set key the manager's `addDevice`
    /// authorizes). Derived from the device's [`DeviceKey`] via
    /// [`pangolin_chain::evm::derive_evm_wallet`].
    pub signer: [u8; SIGNER_LEN],
    /// The 16-byte freshness nonce the NEW device generated. Both devices'
    /// SAS derivation consumes the SAME nonce; a mismatch in
    /// [`crate::pairing_transport`]-FFI's `pairing_derive_sas` fails CLOSED
    /// (§0a Q-c).
    pub freshness_nonce: [u8; FRESHNESS_NONCE_LEN],
}

/// Errors a decode (byte or string) can surface. Deliberately COARSE — no
/// payload bytes / no secret material in any `Display` (L4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum PairingTransportError {
    /// The byte buffer / decoded text was not exactly [`PAYLOAD_LEN`]
    /// bytes (after stripping the text form's checksum, when applicable).
    #[error("pairing payload wrong length")]
    WrongLength,
    /// The payload's leading [`DOMAIN`] prefix did not match — the bytes
    /// are NOT a pangolin pairing payload (or are a payload under a
    /// DIFFERENT domain version).
    #[error("pairing payload domain mismatch")]
    DomainMismatch,
    /// The payload's `schema_version` byte is not [`SCHEMA_VERSION`]. A
    /// future version's payload presented to a build that does not know
    /// it fails CLOSED here.
    #[error("pairing payload unsupported schema version")]
    UnsupportedVersion,
    /// The text form's 4-byte truncated-SHA-256 checksum did not match
    /// the recomputed checksum of the decoded payload bytes (tampered or
    /// transcription-corrupted text).
    #[error("pairing payload checksum mismatch")]
    ChecksumMismatch,
    /// The text form contained a character outside the lowercase base32
    /// (`a-z` + `2-7`) alphabet, or was otherwise structurally invalid
    /// (e.g. zero-length).
    #[error("pairing payload text invalid encoding")]
    InvalidEncoding,
}

// ---------------------------------------------------------------------------
// Byte-form codec — fixed-layout, length-strict, version-gated
// ---------------------------------------------------------------------------

/// Encode a [`PairingPayload`] to its fixed-layout byte form.
///
/// The output is exactly [`PAYLOAD_LEN`] bytes; the layout is the one
/// documented at the module level (DOMAIN ‖ schema_version ‖ vault_id ‖
/// device_id ‖ x25519_pairing_pub ‖ signer ‖ freshness_nonce). The encoder
/// stamps `payload.schema_version` verbatim — callers building a NEW payload
/// MUST set it to [`SCHEMA_VERSION`] (the FFI does this for them).
///
/// Deterministic: same input ⇒ same output, byte-identical. Re-encoding any
/// decoded payload round-trips byte-identical (pinned by the property test
/// [`tests::encode_decode_round_trip_is_byte_identical`]).
#[must_use]
pub fn encode_bytes(payload: &PairingPayload) -> Vec<u8> {
    let mut out = Vec::with_capacity(PAYLOAD_LEN);
    out.extend_from_slice(DOMAIN);
    out.push(payload.schema_version);
    out.extend_from_slice(&payload.vault_id);
    out.extend_from_slice(&payload.device_id);
    out.extend_from_slice(&payload.x25519_pairing_pub);
    out.extend_from_slice(&payload.signer);
    out.extend_from_slice(&payload.freshness_nonce);
    debug_assert_eq!(
        out.len(),
        PAYLOAD_LEN,
        "encode_bytes drift — PAYLOAD_LEN constant out of sync with the layout"
    );
    out
}

/// Decode a fixed-layout byte payload back into a [`PairingPayload`].
///
/// Six-step gate (each failure CLOSED with a typed error):
///
/// 1. **Length.** Reject anything ≠ [`PAYLOAD_LEN`] →
///    [`PairingTransportError::WrongLength`].
/// 2. **Domain.** Reject any leading-prefix mismatch →
///    [`PairingTransportError::DomainMismatch`].
/// 3. **Schema version.** Reject any byte ≠ [`SCHEMA_VERSION`] →
///    [`PairingTransportError::UnsupportedVersion`].
/// 4-6. **Field extraction.** Pull each fixed-offset slice into its
///    fixed-size array; the extraction itself cannot fail (the length
///    check guaranteed the slices are valid).
///
/// # Errors
///
/// [`PairingTransportError::WrongLength`] / `DomainMismatch` /
/// `UnsupportedVersion` per the gate above. NEVER `ChecksumMismatch` or
/// `InvalidEncoding` (those are text-form only).
pub fn decode_bytes(bytes: &[u8]) -> Result<PairingPayload, PairingTransportError> {
    if bytes.len() != PAYLOAD_LEN {
        return Err(PairingTransportError::WrongLength);
    }
    if &bytes[..DOMAIN.len()] != DOMAIN {
        return Err(PairingTransportError::DomainMismatch);
    }
    let schema_version = bytes[OFFSET_SCHEMA_VERSION];
    if schema_version != SCHEMA_VERSION {
        return Err(PairingTransportError::UnsupportedVersion);
    }
    let mut vault_id = [0u8; VAULT_ID_LEN];
    vault_id.copy_from_slice(&bytes[OFFSET_VAULT_ID..OFFSET_VAULT_ID + VAULT_ID_LEN]);
    let mut device_id = [0u8; DEVICE_ID_LEN];
    device_id.copy_from_slice(&bytes[OFFSET_DEVICE_ID..OFFSET_DEVICE_ID + DEVICE_ID_LEN]);
    let mut x25519_pairing_pub = [0u8; X25519_KEY_LEN];
    x25519_pairing_pub
        .copy_from_slice(&bytes[OFFSET_PAIRING_PUB..OFFSET_PAIRING_PUB + X25519_KEY_LEN]);
    let mut signer = [0u8; SIGNER_LEN];
    signer.copy_from_slice(&bytes[OFFSET_SIGNER..OFFSET_SIGNER + SIGNER_LEN]);
    let mut freshness_nonce = [0u8; FRESHNESS_NONCE_LEN];
    freshness_nonce.copy_from_slice(
        &bytes[OFFSET_FRESHNESS_NONCE..OFFSET_FRESHNESS_NONCE + FRESHNESS_NONCE_LEN],
    );
    Ok(PairingPayload {
        schema_version,
        vault_id,
        device_id,
        x25519_pairing_pub,
        signer,
        freshness_nonce,
    })
}

// ---------------------------------------------------------------------------
// Text-form codec — base32 (RFC 4648, lowercase, no padding) + 4-byte SHA-256
// checksum so a manually-typed / clipboard-copy-paste payload that drifts
// fails CLOSED instead of silently smuggling tampered bytes through.
// ---------------------------------------------------------------------------

/// The 32-character lowercase base32 alphabet (RFC 4648 §6) used by the
/// text encoder. NOT base32hex (`0-9a-v`) — RFC 4648 standard base32 is
/// `a-z` (10 + 22 letters trimmed to 26) joined with `2-7` (`8` and `9`
/// removed to avoid visual confusion with `B` and `q`). Lowercase form
/// chosen for keyboard-friendly typing.
const BASE32_ALPHABET: &[u8; 32] = b"abcdefghijklmnopqrstuvwxyz234567";

/// Encode a [`PairingPayload`] to its TEXT form — a lowercase
/// base32-no-padding string of length ⌈((PAYLOAD_LEN +
/// TEXT_CHECKSUM_LEN) × 8) / 5⌉. Roughly 142 characters at
/// `SCHEMA_VERSION = 2`. The string is alphanumeric (`a-z` + `2-7`), no
/// padding, copy-paste-friendly across SMS / email / clipboard.
///
/// The 4-byte truncated SHA-256 checksum of the payload bytes is appended
/// BEFORE base32-encoding — so a single-character transcription error in
/// the visible text fails CLOSED at decode (overwhelming probability —
/// the checksum's 4-byte length gives 2^-32 collision probability for an
/// adversarial flip; for a human typo the failure is virtually certain).
#[must_use]
pub fn encode_string(payload: &PairingPayload) -> String {
    let bytes = encode_bytes(payload);
    let checksum = payload_checksum(&bytes);
    let mut buf = Vec::with_capacity(bytes.len() + TEXT_CHECKSUM_LEN);
    buf.extend_from_slice(&bytes);
    buf.extend_from_slice(&checksum);
    base32_encode(&buf)
}

/// Decode a TEXT-form payload back into a [`PairingPayload`].
///
/// Six-step gate:
/// 1. **Alphabet.** Every char must be in `a-z` (lowercase, RFC 4648) or
///    `2-7`; any other byte ⇒ [`PairingTransportError::InvalidEncoding`].
///    Whitespace is REJECTED — the host strips before calling.
/// 2. **Length.** The base32-decoded bytes must be exactly
///    `PAYLOAD_LEN + TEXT_CHECKSUM_LEN` — anything else ⇒ `WrongLength`.
/// 3. **Checksum.** The trailing 4 bytes must match
///    `sha256(payload_bytes)[..4]` — else `ChecksumMismatch`.
/// 4-6. The first [`PAYLOAD_LEN`] bytes pass through [`decode_bytes`]
///    for the byte-form gate (domain / version / field extraction).
///
/// # Errors
///
/// [`PairingTransportError::InvalidEncoding`] / `WrongLength` /
/// `ChecksumMismatch` / `DomainMismatch` / `UnsupportedVersion`.
pub fn decode_string(s: &str) -> Result<PairingPayload, PairingTransportError> {
    let decoded = base32_decode(s.as_bytes())?;
    if decoded.len() != PAYLOAD_LEN + TEXT_CHECKSUM_LEN {
        return Err(PairingTransportError::WrongLength);
    }
    let (payload_bytes, checksum) = decoded.split_at(PAYLOAD_LEN);
    let expected = payload_checksum(payload_bytes);
    // Bytewise compare — the checksum is non-secret context, so a
    // short-circuit does not leak a side-channel.
    if checksum != expected {
        return Err(PairingTransportError::ChecksumMismatch);
    }
    decode_bytes(payload_bytes)
}

/// Compute the truncated-SHA-256 checksum the TEXT form appends.
///
/// Uses `sha2::Sha256` (already pulled at the workspace level via
/// `pangolin-crypto` — naming it here adds no new external crate, see
/// `Cargo.toml`). 4 bytes is sufficient — the checksum's purpose is
/// transcription-error detection, NOT MITM defense (the SAS handles
/// MITM, L2).
fn payload_checksum(bytes: &[u8]) -> [u8; TEXT_CHECKSUM_LEN] {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(bytes);
    let mut out = [0u8; TEXT_CHECKSUM_LEN];
    out.copy_from_slice(&digest[..TEXT_CHECKSUM_LEN]);
    out
}

/// RFC 4648 base32 lowercase, no padding. Hand-rolled (L6 — no new
/// external crate). Pure byte-in/string-out; never allocates beyond the
/// output buffer.
fn base32_encode(bytes: &[u8]) -> String {
    // Each 5-byte group ⇒ 8 chars; the last (incomplete) group writes
    // ⌈leftover_bits / 5⌉ chars (no padding, RFC 4648 §6 "without
    // padding").
    let nbits = bytes.len() * 8;
    let nchars = nbits.div_ceil(5);
    let mut out = String::with_capacity(nchars);
    let mut buf = 0u64;
    let mut bits = 0u32;
    for &b in bytes {
        buf = (buf << 8) | u64::from(b);
        bits += 8;
        while bits >= 5 {
            bits -= 5;
            let idx = ((buf >> bits) & 0x1F) as usize;
            out.push(char::from(BASE32_ALPHABET[idx]));
        }
    }
    if bits > 0 {
        let idx = ((buf << (5 - bits)) & 0x1F) as usize;
        out.push(char::from(BASE32_ALPHABET[idx]));
    }
    debug_assert_eq!(out.len(), nchars);
    out
}

/// RFC 4648 base32 lowercase decode (no padding). Returns
/// [`PairingTransportError::InvalidEncoding`] on any char outside
/// `a-z2-7`. Lowercase-only; an uppercase letter or whitespace is rejected
/// (the host normalizes input before calling). Hand-rolled (L6).
fn base32_decode(bytes: &[u8]) -> Result<Vec<u8>, PairingTransportError> {
    if bytes.is_empty() {
        return Err(PairingTransportError::InvalidEncoding);
    }
    let mut out = Vec::with_capacity(bytes.len() * 5 / 8);
    let mut buf = 0u64;
    let mut bits = 0u32;
    for &c in bytes {
        let idx = base32_decode_char(c)?;
        buf = (buf << 5) | u64::from(idx);
        bits += 5;
        if bits >= 8 {
            bits -= 8;
            let byte = ((buf >> bits) & 0xFF) as u8;
            out.push(byte);
        }
    }
    // RFC 4648 §6: the trailing partial-bits MUST be zero for a
    // canonical encode (no padding). A non-zero trailing fragment means
    // either the encoded bytes were not a whole multiple OR the encoder
    // emitted non-canonical bytes — reject so a re-encode is always
    // byte-identical (L4 round-trip property).
    if bits > 0 && (buf & ((1u64 << bits) - 1)) != 0 {
        return Err(PairingTransportError::InvalidEncoding);
    }
    Ok(out)
}

/// Map a base32-alphabet char (lowercase a-z + 2-7) to its 5-bit value;
/// any other char ⇒ [`PairingTransportError::InvalidEncoding`].
fn base32_decode_char(c: u8) -> Result<u8, PairingTransportError> {
    match c {
        b'a'..=b'z' => Ok(c - b'a'),
        b'2'..=b'7' => Ok(c - b'2' + 26),
        _ => Err(PairingTransportError::InvalidEncoding),
    }
}

// ---------------------------------------------------------------------------
// Generic checksummed-text encoding for arbitrary non-secret byte blobs
// (the #106e-2 FFI re-uses this shape for the sealed-VDK envelope so the
// host has ONE text-form decoder — base32-no-padding + a 4-byte
// truncated SHA-256 checksum — for both the pairing payload AND the
// envelope).
// ---------------------------------------------------------------------------

/// **#106e-2 helper.** Encode an arbitrary byte buffer to the symmetric
/// base32-no-padding text form the pairing payload uses, with a 4-byte
/// truncated-SHA-256 checksum appended pre-encode.
///
/// Used by [`crate::pairing_transport`]-FFI for the `SealedVdkForDevice`
/// envelope: the host receives ONE text form per artifact (pairing
/// payload + sealed-VDK envelope) so UI / clipboard / SMS shipping is
/// consistent. Non-secret — the envelope's contents are already sealed
/// to the recipient's pairing pubkey.
#[must_use]
pub fn encode_text_with_checksum(bytes: &[u8]) -> String {
    let checksum = payload_checksum(bytes);
    let mut buf = Vec::with_capacity(bytes.len() + TEXT_CHECKSUM_LEN);
    buf.extend_from_slice(bytes);
    buf.extend_from_slice(&checksum);
    base32_encode(&buf)
}

/// **#106e-2 helper.** Decode a checksummed base32-text-form byte blob
/// back to the original bytes (the inverse of [`encode_text_with_checksum`]).
///
/// # Errors
///
/// [`PairingTransportError::InvalidEncoding`] for a non-base32 char,
/// [`PairingTransportError::WrongLength`] for a decoded buffer too short
/// to even hold a checksum, [`PairingTransportError::ChecksumMismatch`]
/// for a bad checksum.
pub fn decode_text_with_checksum(s: &str) -> Result<Vec<u8>, PairingTransportError> {
    let decoded = base32_decode(s.as_bytes())?;
    if decoded.len() < TEXT_CHECKSUM_LEN {
        return Err(PairingTransportError::WrongLength);
    }
    let split = decoded.len() - TEXT_CHECKSUM_LEN;
    let (body, checksum) = decoded.split_at(split);
    let expected = payload_checksum(body);
    if checksum != expected {
        return Err(PairingTransportError::ChecksumMismatch);
    }
    Ok(body.to_vec())
}

// ---------------------------------------------------------------------------
// Error mapping into pangolin_core::Error (the FFI / chain-of-errors join
// point — exactly the #106c discipline)
// ---------------------------------------------------------------------------

impl From<PairingTransportError> for crate::Error {
    /// Map every transport-decode failure to a `Validation { kind: "argument" }`
    /// — the same shape the #106c / #106e-1 FFI bindings use for length /
    /// shape failures, so the FFI surface treats a malformed payload the
    /// same way as any other bad host-supplied bytes (no oracle on the
    /// specific reason; the variant DISCRIMINANT is for engine-side
    /// branching only).
    fn from(err: PairingTransportError) -> Self {
        Self::Validation {
            kind: "argument".into(),
            message: err.to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_payload() -> PairingPayload {
        PairingPayload {
            schema_version: SCHEMA_VERSION,
            vault_id: [0x11; VAULT_ID_LEN],
            device_id: [0x22; DEVICE_ID_LEN],
            x25519_pairing_pub: [0x33; X25519_KEY_LEN],
            signer: [0x44; SIGNER_LEN],
            freshness_nonce: [0x55; FRESHNESS_NONCE_LEN],
        }
    }

    /// L4: the payload length is exactly the documented constant. A drift
    /// in any field length fires here.
    #[test]
    fn payload_length_is_exact_constant() {
        // 27 (DOMAIN) + 1 + 32 + 32 + 32 + 20 + 16 = 160 bytes (the spec).
        assert_eq!(DOMAIN.len(), 27, "domain prefix length pin");
        assert_eq!(
            PAYLOAD_LEN, 160,
            "payload byte length is pinned (spec §3.A)"
        );
        let b = encode_bytes(&sample_payload());
        assert_eq!(b.len(), PAYLOAD_LEN);
    }

    /// L4 round-trip: encode → decode reconstructs the identical payload
    /// (every field byte-equal); the re-encode then equals the original
    /// bytes (the byte-identity property the audit pins).
    #[test]
    fn encode_decode_round_trip_is_byte_identical() {
        let p = sample_payload();
        let b1 = encode_bytes(&p);
        let decoded = decode_bytes(&b1).unwrap();
        assert_eq!(decoded, p);
        let b2 = encode_bytes(&decoded);
        assert_eq!(b1, b2, "round-trip must be byte-identical (L4)");
    }

    /// The TEXT form round-trips byte-identical AND yields the same
    /// payload as the BYTE form.
    #[test]
    fn text_form_round_trip_is_byte_identical() {
        let p = sample_payload();
        let s = encode_string(&p);
        let decoded = decode_string(&s).unwrap();
        assert_eq!(decoded, p);
        let s2 = encode_string(&decoded);
        assert_eq!(s, s2, "text re-encode must be byte-identical");
        // Confirm the text alphabet is lowercase base32 (a-z + 2-7).
        for c in s.bytes() {
            assert!(
                c.is_ascii_lowercase() || (b'2'..=b'7').contains(&c),
                "text-form byte outside base32 alphabet: {c}"
            );
        }
    }

    /// Length-negative: a too-short / too-long byte buffer rejects with
    /// `WrongLength`.
    #[test]
    fn decode_bytes_wrong_length_rejected() {
        let p = sample_payload();
        let mut short = encode_bytes(&p);
        short.pop();
        assert_eq!(
            decode_bytes(&short),
            Err(PairingTransportError::WrongLength)
        );
        let mut long = encode_bytes(&p);
        long.push(0);
        assert_eq!(decode_bytes(&long), Err(PairingTransportError::WrongLength));
        assert_eq!(decode_bytes(&[]), Err(PairingTransportError::WrongLength));
    }

    /// Domain-negative: a buffer whose leading prefix is NOT [`DOMAIN`]
    /// rejects with `DomainMismatch`.
    #[test]
    fn decode_bytes_domain_mismatch_rejected() {
        let p = sample_payload();
        let mut tampered = encode_bytes(&p);
        // Flip a byte INSIDE the domain prefix.
        tampered[0] ^= 0x01;
        assert_eq!(
            decode_bytes(&tampered),
            Err(PairingTransportError::DomainMismatch)
        );
    }

    /// Version-negative: a buffer whose schema_version byte is not
    /// [`SCHEMA_VERSION`] rejects with `UnsupportedVersion`.
    #[test]
    fn decode_bytes_unsupported_version_rejected() {
        let p = sample_payload();
        let mut tampered = encode_bytes(&p);
        tampered[OFFSET_SCHEMA_VERSION] = SCHEMA_VERSION.wrapping_add(1);
        assert_eq!(
            decode_bytes(&tampered),
            Err(PairingTransportError::UnsupportedVersion)
        );
        // Also reject 0 / 1 explicitly (DeviceAuthFields v=1 must NOT
        // shadow this — the domain prefix already differs, but this is
        // belt-and-braces).
        tampered[OFFSET_SCHEMA_VERSION] = 0;
        assert_eq!(
            decode_bytes(&tampered),
            Err(PairingTransportError::UnsupportedVersion)
        );
        tampered[OFFSET_SCHEMA_VERSION] = 1;
        assert_eq!(
            decode_bytes(&tampered),
            Err(PairingTransportError::UnsupportedVersion)
        );
    }

    /// Text-form checksum-negative: flipping a single character in the
    /// text body rejects with `ChecksumMismatch`.
    #[test]
    fn decode_string_checksum_mismatch_rejected() {
        let p = sample_payload();
        let s = encode_string(&p);
        let mut tampered: Vec<u8> = s.into_bytes();
        // Flip a single character (find a position that's not the very
        // first byte — DOMAIN bytes mostly land in the first chars but a
        // flip there could trigger DomainMismatch after checksum check).
        // The checksum check runs BEFORE the byte-form gate, so ANY
        // single-char flip in either the payload or the checksum body
        // surfaces ChecksumMismatch first.
        let mid = tampered.len() / 2;
        // Find a flip that lands within the lowercase alphabet.
        let original = tampered[mid];
        tampered[mid] = if original == b'a' { b'b' } else { b'a' };
        let result = decode_string(std::str::from_utf8(&tampered).unwrap());
        assert_eq!(result, Err(PairingTransportError::ChecksumMismatch));
    }

    /// Text-form encoding-negative: any character outside `a-z2-7` is
    /// rejected with `InvalidEncoding`.
    #[test]
    fn decode_string_invalid_encoding_rejected() {
        assert_eq!(
            decode_string("ABCDEF"),
            Err(PairingTransportError::InvalidEncoding),
            "uppercase rejected"
        );
        assert_eq!(
            decode_string("abc def"),
            Err(PairingTransportError::InvalidEncoding),
            "whitespace rejected"
        );
        assert_eq!(
            decode_string("abc1def"),
            Err(PairingTransportError::InvalidEncoding),
            "digit '1' rejected (outside base32 alphabet)"
        );
        assert_eq!(
            decode_string(""),
            Err(PairingTransportError::InvalidEncoding),
            "empty rejected"
        );
    }

    /// Text-form length-negative: a decoded length that doesn't equal
    /// `PAYLOAD_LEN + TEXT_CHECKSUM_LEN` is `WrongLength`.
    #[test]
    fn decode_string_wrong_length_rejected() {
        // Encode just a 3-byte buffer — the decode will produce 3 bytes,
        // which is ≠ PAYLOAD_LEN + 4.
        let s = base32_encode(&[0x12, 0x34, 0x56]);
        assert_eq!(decode_string(&s), Err(PairingTransportError::WrongLength));
    }

    /// L4 byte-pin: the `DOMAIN` byte-string is distinct from every other
    /// HKDF info / domain string in the codebase (the audit's catch-all).
    /// A drift collapses a domain-separation invariant.
    #[test]
    fn pairing_transport_domain_distinct_from_other_domains() {
        // Every domain string in pangolin-crypto + pangolin-core's tree.
        // A new addition to this list signals a new domain that MUST be
        // checked against `DOMAIN` here.
        let others: &[&[u8]] = &[
            b"pangolin-vdk-wrap-v0",
            b"pangolin-recovery-wrap-v0",
            b"pangolin-guardian-x25519-v0",
            b"pangolin-guardian-x25519-derive-v0",
            pangolin_crypto::pairing::DEVICE_PAIR_X25519_HKDF_INFO,
            pangolin_crypto::pairing::DEVICE_PAIR_X25519_DERIVATION_MESSAGE,
            pangolin_crypto::pairing::DEVICE_WRAP_KEY_INFO,
            b"pangolin-device-pair-seal-v0",
            // The SAS domain (added in pangolin-crypto::pairing for #106e-2);
            // include here for the catch-all distinctness check.
            pangolin_crypto::pairing::SAS_DOMAIN,
        ];
        for o in others {
            assert_ne!(
                DOMAIN, *o,
                "pairing_transport DOMAIN must be distinct from every other domain string"
            );
        }
    }

    /// L4: the schema version is **2** (the byte-pin documented in §0a:
    /// next after #106c's `DeviceAuthFields v=1`). A future bump must
    /// update this constant + this test together.
    #[test]
    fn schema_version_is_pinned_to_two() {
        assert_eq!(SCHEMA_VERSION, 2, "schema version pin (§0a)");
    }

    /// The pairing-transport error maps to a coarse `Validation { kind:
    /// "argument" }` on the `pangolin_core::Error` join — never
    /// `Authentication` (a malformed payload is a parse failure, not an
    /// auth oracle). The FFI then routes the variant straight through.
    #[test]
    fn error_maps_to_validation_argument() {
        for e in [
            PairingTransportError::WrongLength,
            PairingTransportError::DomainMismatch,
            PairingTransportError::UnsupportedVersion,
            PairingTransportError::ChecksumMismatch,
            PairingTransportError::InvalidEncoding,
        ] {
            let core_err: crate::Error = e.into();
            assert!(
                matches!(core_err, crate::Error::Validation { ref kind, .. } if kind == "argument"),
                "pairing-transport error must map to Validation(argument)"
            );
        }
    }

    /// Base32 round-trip on arbitrary byte buffers — pinning the
    /// hand-rolled codec against drift (L6: no new external crate to
    /// vouch for the impl).
    #[test]
    fn base32_round_trips_arbitrary_bytes() {
        for input in [
            &[][..],
            &[0u8][..],
            &[0xFF; 5][..],
            &[0x12, 0x34, 0x56, 0x78, 0x9A][..],
            &[0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE][..],
            // PAYLOAD_LEN bytes — the production size.
            &[0xA5_u8; PAYLOAD_LEN][..],
        ] {
            if input.is_empty() {
                // Empty input decodes back to empty? No — decode rejects
                // empty as InvalidEncoding (an empty payload is never
                // legal). Skip the round-trip case.
                continue;
            }
            let s = base32_encode(input);
            let back = base32_decode(s.as_bytes()).unwrap();
            assert_eq!(back, input, "base32 round-trip drift on {input:?}");
        }
    }
}
