// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by tools/design-tokens-gen — DO NOT EDIT BY HAND.
// Source: apps/design-tokens/tokens.json  schema_version=1
#![forbid(unsafe_code)]
#![allow(clippy::unreadable_literal)]
//! Generated Pangolin UI design-token constants.
//! Source: `apps/design-tokens/tokens.json`. Re-generate via `cargo run -p design-tokens-gen`.

/// The schema version of the source `tokens.json` that produced this file.
pub const SCHEMA_VERSION: u8 = 1;

// --- COLOR ---
pub const COLOR_ACCENT_PRIMARY: &str = "#F2843E";
pub const COLOR_ACCENT_PRIMARY_HOVER: &str = "#E0732D";
pub const COLOR_ACCENT_SECONDARY: &str = "#3E8EF2";
pub const COLOR_BORDER_LIGHT: &str = "#E7E7EB";
pub const COLOR_BORDER_DARK: &str = "#2A2A30";
pub const COLOR_DANGER_LIGHT: &str = "#C42D2D";
pub const COLOR_DANGER_DARK: &str = "#F25555";
pub const COLOR_NEUTRAL_0: &str = "#0A0A0B";
pub const COLOR_NEUTRAL_100: &str = "#1F1F23";
pub const COLOR_NEUTRAL_200: &str = "#2A2A30";
pub const COLOR_NEUTRAL_300: &str = "#3A3A42";
pub const COLOR_NEUTRAL_400: &str = "#5A5A60";
pub const COLOR_NEUTRAL_50: &str = "#141416";
pub const COLOR_NEUTRAL_500: &str = "#7A7A82";
pub const COLOR_NEUTRAL_600: &str = "#9A9AA2";
pub const COLOR_NEUTRAL_700: &str = "#BABAC2";
pub const COLOR_NEUTRAL_800: &str = "#DADAE2";
pub const COLOR_NEUTRAL_900: &str = "#FAFAFB";
pub const COLOR_SCRIM_LIGHT: &str = "rgba(0, 0, 0, 0.4)";
pub const COLOR_SCRIM_DARK: &str = "rgba(0, 0, 0, 0.6)";
pub const COLOR_SUCCESS_LIGHT: &str = "#1F9D55";
pub const COLOR_SUCCESS_DARK: &str = "#3BD27F";
pub const COLOR_SURFACE_LIGHT: &str = "#FFFFFF";
pub const COLOR_SURFACE_DARK: &str = "#141416";
pub const COLOR_SURFACE_ELEVATED_LIGHT: &str = "#F7F7F8";
pub const COLOR_SURFACE_ELEVATED_DARK: &str = "#1F1F23";
pub const COLOR_TEXT_LIGHT: &str = "#0A0A0B";
pub const COLOR_TEXT_DARK: &str = "#FAFAFB";
pub const COLOR_TEXT_MUTED_LIGHT: &str = "#5A5A60";
pub const COLOR_TEXT_MUTED_DARK: &str = "#A4A4AC";
pub const COLOR_WARNING_LIGHT: &str = "#C77A1A";
pub const COLOR_WARNING_DARK: &str = "#F2A94B";

// --- TYPOGRAPHY ---
pub const FONT_FAMILY_MONO: &str = "'JetBrains Mono', ui-monospace, monospace";
pub const FONT_FAMILY_SANS: &str = "'Inter', system-ui, -apple-system, sans-serif";
pub const FONT_LINE_HEIGHT_BASE: &str = "1.5";
pub const FONT_LINE_HEIGHT_LOOSE: &str = "1.75";
pub const FONT_LINE_HEIGHT_TIGHT: &str = "1.2";
pub const FONT_SIZE_2XL: &str = "1.5rem";
pub const FONT_SIZE_BASE: &str = "1rem";
pub const FONT_SIZE_DISPLAY: &str = "2.25rem";
pub const FONT_SIZE_LG: &str = "1.125rem";
pub const FONT_SIZE_SM: &str = "0.875rem";
pub const FONT_SIZE_XL: &str = "1.25rem";
pub const FONT_SIZE_XS: &str = "0.75rem";
pub const FONT_WEIGHT_BOLD: u16 = 700;
pub const FONT_WEIGHT_MEDIUM: u16 = 500;
pub const FONT_WEIGHT_REGULAR: u16 = 400;
pub const FONT_WEIGHT_SEMIBOLD: u16 = 600;

// --- SPACING ---
pub const SPACE_0: &str = "0";
pub const SPACE_1: &str = "0.25rem";
pub const SPACE_12: &str = "3rem";
pub const SPACE_16: &str = "4rem";
pub const SPACE_2: &str = "0.5rem";
pub const SPACE_24: &str = "6rem";
pub const SPACE_3: &str = "0.75rem";
pub const SPACE_4: &str = "1rem";
pub const SPACE_6: &str = "1.5rem";
pub const SPACE_8: &str = "2rem";

// --- RADIUS ---
pub const RADIUS_FULL: &str = "9999px";
pub const RADIUS_LG: &str = "12px";
pub const RADIUS_MD: &str = "8px";
pub const RADIUS_SM: &str = "4px";

// --- ELEVATION (CSS box-shadow stacks) ---
pub const SHADOW_LG: &str = "0 12px 24px rgba(0,0,0,0.14)";
pub const SHADOW_MD: &str = "0 4px 8px rgba(0,0,0,0.10)";
pub const SHADOW_NONE: &str = "none";
pub const SHADOW_SM: &str = "0 1px 2px rgba(0,0,0,0.06)";

// --- MOTION ---
pub const MOTION_DURATION_BASE: &str = "180ms";
pub const MOTION_DURATION_FAST: &str = "100ms";
pub const MOTION_DURATION_SLOW: &str = "280ms";
pub const MOTION_EASING_ACCELERATE: &str = "cubic-bezier(0.4, 0, 1, 1)";
pub const MOTION_EASING_DECELERATE: &str = "cubic-bezier(0, 0, 0.2, 1)";
pub const MOTION_EASING_SPRING: &str = "cubic-bezier(0.34, 1.56, 0.64, 1)";
pub const MOTION_EASING_STANDARD: &str = "cubic-bezier(0.2, 0, 0, 1)";
